### ISSUE TITLE
Exception when a score is missing 

### ISSUE THREAD

**Issue by kittcom2** [preritdas/rottentomatoes-python#31]
I received this exception when an audience score was missing:

>>> movie = rt.Movie('The Beast')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\rottentomatoes\movie.py", line 21, in __init__
    self.audience_score = standalone.audience_score(self.movie_title, content=content)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\rottentomatoes\standalone.py", line 176, in audience_score
    return _get_score_details(content)['scoreboard']['audienceScore']["value"]
KeyError: 'value'
>>>

Please fix to catch this and other possible KeyErrors when extracting info from the web page content.

**Comment by preritdas** [comment]
Publishing as we speak under v0.6.5. @kittcom2
